import { Inter } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "@/utils/provider";
import UiProvider from "./components/ui/UiProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-screen h-screen">
          <ReduxProvider>
            <UiProvider>
              {children}
            </UiProvider>
          </ReduxProvider>
        </div>
      </body>
    </html>
  );
}
